# Generated by Django 5.0 on 2024-01-11 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
