# Generated by Django 5.0 on 2023-12-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="xd",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
