# Generated by Django 5.0 on 2023-12-26 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_cocuk_kitabi_delete_books"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cocuk_kitabi",
            new_name="books",
        ),
    ]
