# Generated by Django 5.0 on 2023-12-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_rename_cocuk_kitabi_books"),
    ]

    operations = [
        migrations.CreateModel(
            name="cocukkitabi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("detail", models.CharField(max_length=1000)),
                ("review", models.CharField(max_length=1000)),
                ("rate", models.IntegerField()),
                ("pdf", models.FileField(blank=True, null=True, upload_to="")),
            ],
        ),
    ]
