# Generated by Django 5.0 on 2023-12-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0006_aksiyon_biyografik_education_gerilim_macera"),
    ]

    operations = [
        migrations.AddField(
            model_name="aksiyon",
            name="cat_id",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="biyografik",
            name="cat_id",
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name="books",
            name="cat_id",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="cocukkitabi",
            name="cat_id",
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="education",
            name="cat_id",
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name="gerilim",
            name="cat_id",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="macera",
            name="cat_id",
            field=models.PositiveIntegerField(default=4),
        ),
    ]
