# Generated by Django 5.0 on 2023-12-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0007_aksiyon_cat_id_biyografik_cat_id_books_cat_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aksiyon",
            name="cat_id",
            field=models.IntegerField(default=5, editable=False),
        ),
        migrations.AlterField(
            model_name="biyografik",
            name="cat_id",
            field=models.IntegerField(default=6, editable=False),
        ),
        migrations.AlterField(
            model_name="books",
            name="cat_id",
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name="cocukkitabi",
            name="cat_id",
            field=models.IntegerField(default=2, editable=False),
        ),
        migrations.AlterField(
            model_name="education",
            name="cat_id",
            field=models.IntegerField(default=7, editable=False),
        ),
        migrations.AlterField(
            model_name="gerilim",
            name="cat_id",
            field=models.IntegerField(default=3, editable=False),
        ),
        migrations.AlterField(
            model_name="macera",
            name="cat_id",
            field=models.IntegerField(default=4, editable=False),
        ),
    ]
