# Generated by Django 5.0 on 2023-12-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0008_alter_aksiyon_cat_id_alter_biyografik_cat_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aksiyon",
            name="cat_id",
        ),
        migrations.RemoveField(
            model_name="biyografik",
            name="cat_id",
        ),
        migrations.RemoveField(
            model_name="books",
            name="cat_id",
        ),
        migrations.RemoveField(
            model_name="cocukkitabi",
            name="cat_id",
        ),
        migrations.RemoveField(
            model_name="education",
            name="cat_id",
        ),
        migrations.RemoveField(
            model_name="gerilim",
            name="cat_id",
        ),
        migrations.RemoveField(
            model_name="macera",
            name="cat_id",
        ),
        migrations.AddField(
            model_name="aksiyon",
            name="catid",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="biyografik",
            name="catid",
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name="books",
            name="catid",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="cocukkitabi",
            name="catid",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="education",
            name="catid",
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name="gerilim",
            name="catid",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="macera",
            name="catid",
            field=models.IntegerField(default=4),
        ),
    ]
