# Generated by Django 5.0 on 2023-12-26 17:16

import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0012_alter_cocukkitabi_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aksiyon",
            name="id",
            field=models.PositiveBigIntegerField(
                default=movies.models.generate_custom_id,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="biyografik",
            name="id",
            field=models.PositiveBigIntegerField(
                default=movies.models.generate_custom_id,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="id",
            field=models.PositiveBigIntegerField(
                default=movies.models.generate_custom_id,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="gerilim",
            name="id",
            field=models.PositiveBigIntegerField(
                default=movies.models.generate_custom_id,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="macera",
            name="id",
            field=models.PositiveBigIntegerField(
                default=movies.models.generate_custom_id,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
