# Generated by Django 5.0 on 2023-12-26 17:35

import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0013_alter_aksiyon_id_alter_biyografik_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="id",
            field=models.PositiveBigIntegerField(
                default=movies.models.generate_custom_id,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
