# Generated by Django 5.0 on 2023-12-26 17:47

import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0016_alter_gerilim_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aksiyon",
            name="id",
            field=models.PositiveBigIntegerField(
                default=movies.models.generate_custom_idaksiyon,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="biyografik",
            name="id",
            field=models.PositiveBigIntegerField(
                default=movies.models.generate_custom_idbiyografik,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="id",
            field=models.PositiveBigIntegerField(
                default=movies.models.generate_custom_ideducation,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="macera",
            name="id",
            field=models.PositiveBigIntegerField(
                default=movies.models.generate_custom_idmacera,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
