# Generated by Django 5.0 on 2023-12-27 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0017_alter_aksiyon_id_alter_biyografik_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="rate",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ]
            ),
        ),
    ]
