# Generated by Django 5.0 on 2023-12-27 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0019_alter_aksiyon_rate_alter_biyografik_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aksiyon",
            name="rate",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="biyografik",
            name="rate",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ]
            ),
        ),
    ]
