# Generated by Django 5.0 on 2023-12-30 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0020_alter_aksiyon_rate_alter_biyografik_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aksiyon",
            name="detail",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="biyografik",
            name="detail",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="books",
            name="detail",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="books",
            name="rate",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="cocukkitabi",
            name="detail",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="cocukkitabi",
            name="rate",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="detail",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="gerilim",
            name="detail",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="gerilim",
            name="rate",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="macera",
            name="detail",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="macera",
            name="rate",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ]
            ),
        ),
    ]
