# Generated by Django 5.0 on 2023-12-30 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0021_alter_aksiyon_detail_alter_biyografik_detail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="rate",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ]
            ),
        ),
    ]
