# Generated by Django 5.0 on 2024-01-09 12:12

import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0024_book_remove_books_review_product_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.PositiveBigIntegerField(
                default=movies.models.generate_custom_ideducation,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
