# Generated by Django 5.0 on 2024-01-09 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0025_alter_book_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book",
                to="movies.book",
            ),
        ),
    ]
