# Generated by Django 5.0 on 2024-01-09 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0026_alter_product_book"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="product",
        ),
        migrations.RemoveField(
            model_name="rating",
            name="product",
        ),
        migrations.AddField(
            model_name="rating",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="movies.book",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="movies.book",
            ),
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
