# Generated by Django 5.0 on 2024-01-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0027_remove_review_product_remove_rating_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aksiyon",
            name="author",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="aksiyon",
            name="image",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="biyografik",
            name="author",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="biyografik",
            name="image",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="books",
            name="author",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="books",
            name="image",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="cocukkitabi",
            name="author",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cocukkitabi",
            name="image",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="education",
            name="author",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="image",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="gerilim",
            name="author",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="gerilim",
            name="image",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="macera",
            name="author",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="macera",
            name="image",
            field=models.TextField(blank=True),
        ),
    ]
