# Generated by Django 5.0 on 2024-01-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0028_aksiyon_author_aksiyon_image_biyografik_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="review",
            field=models.CharField(default="-", max_length=1000),
        ),
        migrations.AlterField(
            model_name="aksiyon",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="aksiyon",
            name="review",
            field=models.CharField(default="-", max_length=1000),
        ),
        migrations.AlterField(
            model_name="biyografik",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="biyografik",
            name="review",
            field=models.CharField(default="-", max_length=1000),
        ),
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="books",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="cocukkitabi",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="cocukkitabi",
            name="review",
            field=models.CharField(default="-", max_length=1000),
        ),
        migrations.AlterField(
            model_name="education",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="education",
            name="review",
            field=models.CharField(default="-", max_length=1000),
        ),
        migrations.AlterField(
            model_name="gerilim",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="gerilim",
            name="review",
            field=models.CharField(default="-", max_length=1000),
        ),
        migrations.AlterField(
            model_name="macera",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="macera",
            name="review",
            field=models.CharField(default="-", max_length=1000),
        ),
    ]
