# Generated by Django 5.0 on 2024-01-11 11:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0031_customuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rating",
            name="book",
        ),
        migrations.RemoveField(
            model_name="rating",
            name="user",
        ),
        migrations.RemoveField(
            model_name="review",
            name="book",
        ),
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
        migrations.DeleteModel(
            name="Rating",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
